version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    groups:
      npm-dependencies:
        patterns:
          - '*'

  - package-ecosystem: 'gradle'
    directory: '/'
    schedule:
      interval: 'weekly'
    groups:
      gradle-dependencies:
        patterns:
          - '*'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    groups:
      github-actions:
        patterns:
          - '*'

  - package-ecosystem: 'docker'
    directory: '/'
    schedule:
      interval: 'weekly'
    groups:
      docker-images:
        patterns:
          - '*'

  - package-ecosystem: 'docker-compose'
    directories:
      - '/'
      - '/ops/ci'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 1
